ca:
  env: prod
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.101.173.52:3306/ca?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: caserver
      password: bhnd%$..ivhs
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    host: 39.101.173.52
    port: 6379
    password: caserver
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 300ms

mybatis:
  configuration:
    map-underscore-to-camel-case: true #驼峰转换
  mapper-locations: classpath:mapper/*.xml #mapper文件位置
  type-aliases-package: com.card.alumni.entity #实体位置

pagehelper:
  helperDialect: mysql #数据库类型
  reasonable: false #分页参数合理化，最小值不能小于0，最大值不能超过行数
  supportMethodsArguments: true
  params: count=countSql
  rowBoundsWithCount: true
  offsetAsPageNum: true #pageNum=offset pageSize=limit

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间/毫秒，6小时 = 21600000  1小时 = 3600000 7天 = 604800000
  expiration: 604800000
  # 在线用户key
  online: config-web-online-token
  # 验证码
  codeKey: code-key

swagger:
  enable: true
  title: ca-config-web
  description: 卡片校友配置台
  author: liumingyu
  version: 1.0.0
  base-package: com.card.alumni.controller

logging:
  level:
    cn.code.chameleon: error
    org.springframework.web: error
  config: classpath:log/log4j2.xml

qiniu:
  ACCESS_KEY: QCD7SK9ep1JmmGDFQm2cr4PddkKVHVodtMFa9P9A
  SECRET_KEY: EdOOpUTsU9TXKw3GNGQX3NCBjrP6H_WYB_OZhdM5
  bucket: caoos