ca:
  env: prod
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.105.149.158:3306/ca?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: ca
      password: 853zaSSGB7SPkAfM
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    host: 47.105.149.158
    port: 6379
    password: caserver
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 3000ms
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true #驼峰转换
  mapper-locations: classpath:mapper/*.xml #mapper文件位置
  type-aliases-package: com.card.alumni.entity #实体位置

pagehelper:
  helperDialect: mysql #数据库类型
  reasonable: false #分页参数合理化，最小值不能小于0，最大值不能超过行数
  supportMethodsArguments: true
  params: count=countSql
  rowBoundsWithCount: true
  offsetAsPageNum: true #pageNum=offset pageSize=limit

swagger:
  enable: false

logging:
  level:
    cn.code.chameleon: error
    org.springframework.web: error
  config: classpath:log/log4j2.xml